### ISSUE TITLE
构建后assets下的图片资源被放到根目录上了

### ISSUE THREAD

**Issue by CrystalGrape** [ng-docs/ng-docs.github.io#136]
1.在assets目录下创建了img目录用于存放图片资源。
2.在less中使用图片资源，比如：
```less
.background {
    ...
    background-image: url(../../../assets/img/三级背景.jpg);  
}
```
3.构建项目
4.构建完成后dist目录下会发现"三级背景.jpg"这张图片被放到了根目录下，名字也变成了“三级背景.1da8c60eccfc3cf0e564.jpg”。
**这种方式是angular的什么功能呢。另外，我能否避免这个功能？比如我的这张图片本来是在assets下的，能否在构建完成后图片依然在assets目录下。**
